### ISSUE TITLE
Converting Maria1km benchmark outputs to netCDF

### ISSUE THREAD

**Issue by kserradell** [MichaelLaufer/WRF-ADIOS2-to-NetCDF4#2]
Hello Michael

I've been able to successfully produce ADIOS2 outputs with WRF 4.5.1 and the [maria1km benchmark case](https://www2.mmm.ucar.edu/wrf/users/benchmark/v44/benchdata_v44.html). Congrats on the work done. It's a really nice development.

Regarding performance, I've been able to reduce from 5.13219s (Synchronous PnetCDF) to 1.07237s (ADIOS2), which is a very good first result. I'm using the following configuration:

```
 &namelist_adios2
 adios2_compression_enable = .false.,
 adios2_numaggregators = 256,
 /
```

In case you ask, I have not been able to make compression work.

The issue comes when using this converter (which is really key to potentially consider ADIOS2 a production filetype). I'm not able to produce a working netCDF (it's basically empty).

```
python convert.py --input ../WRFV4.5.1/run_maria1km/wrfout_d02_2017-09-20_09\:00\:00/ --output converted.nc
ncdump -h converted.nc
netcdf converted {
dimensions:
	Time = 1 ;
}

```
And BP folder seems to contain valid data...

```
bpls ../WRFV4.5.1/run_maria1km/wrfout_d02_2017-09-20_09\:00\:00/
  float    ACGRDFLX               {1590, 1660}
  float    ACHFX                  {1590, 1660}
  float    ACLHF                  {1590, 1660}
  float    ACLWDNB                {1590, 1660}
  float    ACLWDNBC               {1590, 1660}
  float    ACLWDNT                {1590, 1660}
  ...
```

Any ideas?

**Comment by MichaelLaufer** [comment]
Hi @kserradell ,
Thanks for reaching out. 
If possible can you send me a small dataset that I can debug this, with along with expected output?

**Comment by kserradell** [comment]
Thanks for your quick answer, @MichaelLaufer !

I've been able to tar.gz a single output.

https://drive.google.com/file/d/1e1qa3bZWhct5yCg_WGF331xZDK7LaNPn/view?usp=drive_link

Expected output is a WRF standard file.

Thanks for taking a look.

KiM

**Comment by MichaelLaufer** [comment]
Thanks for providing that Kim, it lead to a quick resolution.
It seems that this issue is due to the new format BP5 and extremely large files.
See here: https://github.com/ornladios/ADIOS2/issues/3678 

Changing the open mode to `rra` fixes the issue and I am able to convert the file without issue.
I will work on fixing this here but meanwhile:
```
diff --git a/convert.py b/convert.py
index 735c06a..5dd42ae 100644
--- a/convert.py
+++ b/convert.py
@@ -1,10 +1,11 @@
-import os, sys
 import argparse
+import os
+import sys
 from collections import defaultdict

+import adios2
 import numpy as np
 from netCDF4 import Dataset
-import adios2

 try:
     from mpi4py import MPI
@@ -42,7 +43,7 @@ def open_files(input_file, output_file, parallel=False, diskless=False):
     if parallel:
         adios2f = adios2.open(input_file, "r", comm=MPI.COMM_WORLD)
     else:
-        adios2f = adios2.open(input_file, "r")
+        adios2f = adios2.open(input_file, "rra")
     netcdff = Dataset(
         output_file,
         "w",
```

Moving forward, in a production environment it may make sense to port this script c++, which I would assume would reduce the conversion time.

**Comment by kserradell** [comment]
Michael!

It worked and produced a very nice WRF file (with all vars and attributes)!

Even sequentially, it produced the file in 7s.

Awesome! This is really promising!

I will keep you updated.

KiM
